import type { ShowroomCollection, ShowroomProject } from './types'

// Add a collection here, then add its projects below. The room, modal and
// accessible fallback consume this data; no scene or player changes are needed.
export const showroomCollections: ShowroomCollection[] = [
  {
    id: 'hospitality',
    label: 'Hospitality',
    subtitle: 'Three creative directions. One production system.',
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    subtitle: 'Architecture, lifestyle and cinematic property storytelling.',
  },
  {
    id: 'micro-stories',
    label: 'Micro Stories',
    subtitle: 'Short-form cinematic narratives with synthetic characters.',
  },
  {
    id: 'original-worlds',
    label: 'Original Worlds',
    subtitle: 'Original animated worlds, characters and stories built with AI.',
    emptyState: {
      heading: 'Original animated series in development',
      description: 'Original characters, environments and episodic storytelling exploring AI-first animation.',
    },
  },
]

// These are speculative ATELIER demonstrations, never client commissions.
// YouTube hosts the streams; the repository only contains optimized posters.
export const showroom: ShowroomProject[] = [
  {
    id: 'hospitality-001',
    collection: 'hospitality',
    collectionLabel: 'Hospitality',
    index: '001',
    title: 'Brand Experience',
    conceptLine: 'One Group. Many Worlds.',
    sector: 'Hospitality',
    status: 'ATELIER POC',
    hero: {
      type: 'video',
      thumbnail: 'portfolio/showroom/hospitality/concept-001/thumbnail.webp',
      youtubeId: '9pNYF_Eyk1Y',
    },
    watchUrl: 'https://youtu.be/9pNYF_Eyk1Y',
    description: 'A speculative hospitality campaign exploring how one creative language can move across restaurant, bar and nightlife environments.',
    extendedDescription: 'Built as a screen-first brand film, the concept focuses on atmosphere, product, architecture, texture and human experience — creating a unified visual standard across multiple venues.',
    territories: ['Restaurant', 'Bar', 'Nightlife', 'Hospitality Groups', 'Digital Signage'],
    capabilities: ['Cinematic advertising', 'Food and beverage direction', 'Architectural atmosphere', 'Premium lighting', 'Brand consistency', 'Multi-venue creative systems'],
    applications: ['Digital signage', 'Venue screens', 'Commercial', 'Event display', 'Web', 'Social cutdown'],
    featured: true,
    latest: true,
    latestType: 'film',
    accent: '#d0a46e',
  },
  {
    id: 'hospitality-002',
    collection: 'hospitality',
    collectionLabel: 'Hospitality',
    index: '002',
    title: 'The Night Moves',
    conceptLine: 'Youth. Status. Motion. Scale.',
    sector: 'Hospitality',
    status: 'ATELIER POC',
    hero: {
      type: 'video',
      thumbnail: 'portfolio/showroom/hospitality/concept-002/thumbnail.webp',
      youtubeId: 'wNpkoSjUNOk',
    },
    watchUrl: 'https://youtu.be/wNpkoSjUNOk',
    description: 'A speculative entertainment and hospitality campaign built around movement, youth culture and escalating scale.',
    extendedDescription: 'From casino dining to young elite nightlife and massive live events, The Night Moves explores a kinetic advertising language driven by human energy, camera movement, rhythm and spectacle.',
    territories: ['Casino Hospitality', 'Young Elite Clubs', 'Nightlife', 'Massive Events', 'Entertainment Groups'],
    capabilities: ['Human blocking', 'Crowd direction', 'Kinetic cinematography', 'Youth-oriented advertising', 'Event-scale spectacle', 'High-energy editing'],
    applications: ['Venue screens', 'Commercial', 'Event display', 'Web', 'Social cutdown'],
    featured: false,
    accent: '#bc7892',
  },
  {
    id: 'hospitality-003',
    collection: 'hospitality',
    collectionLabel: 'Hospitality',
    index: '003',
    title: 'Inside the Invitation',
    conceptLine: 'Private reality becomes impossible.',
    sector: 'Hospitality',
    status: 'ATELIER POC',
    hero: {
      type: 'video',
      thumbnail: 'portfolio/showroom/hospitality/concept-003/thumbnail.webp',
      youtubeId: 'cZgG3cKVMCI',
    },
    watchUrl: 'https://youtu.be/cZgG3cKVMCI',
    description: 'A private pool party becomes something impossible.',
    extendedDescription: 'Inside the Invitation combines cinematic FPV movement, premium mixology, DJ-driven energy, young private-rave culture and fantasy world-building to demonstrate an experiential approach to hospitality advertising.',
    territories: ['Private Parties', 'Pool Experiences', 'Private Clubs', 'Mixology', 'Electronic Music', 'Experiential Hospitality'],
    capabilities: ['Cinematic FPV', 'Fantasy world-building', 'AI-assisted VFX', 'Mixology macro direction', 'DJ / music synchronization', 'Water and creature effects', 'Experiential advertising'],
    applications: ['Digital signage', 'Venue screens', 'Commercial', 'Event display', 'Web', 'Social cutdown'],
    featured: false,
    accent: '#7797c4',
  },
  {
    id: 'real-estate-001',
    collection: 'real-estate',
    collectionLabel: 'Real Estate',
    index: '001',
    title: 'ALBA DISTRICT',
    conceptLine: 'A fictional development. A complete visual world.',
    sector: 'Real Estate',
    status: 'ATELIER POC',
    hero: {
      type: 'video',
      thumbnail: 'portfolio/showroom/real-estate/concept-001/thumbnail.webp',
      youtubeId: 'jK91wfrCGEY',
    },
    watchUrl: 'https://youtu.be/jK91wfrCGEY',
    description: 'A fictional luxury residential development built from the ground up with AI — from masterplan and architecture to interiors, lifestyle and cinematic real estate filmmaking.',
    extendedDescription: 'From masterplanning and architectural visualization to lifestyle, interiors, amenities and cinematic camera direction, the entire project was developed as one coherent visual world before being translated into motion. The concept demonstrates how AI can move beyond isolated renders and create a believable property campaign with spatial, material and cinematic continuity.',
    territories: ['Luxury Residential', 'Real Estate Development', 'Architecture', 'Property Marketing', 'Amenities', 'Residential Lifestyle'],
    capabilities: ['Masterplanning', 'Architectural visualization', 'Spatial continuity', 'Interior visualization', 'Cinematic real-estate direction', 'AI camera choreography', 'Lifestyle direction', 'Environmental world-building'],
    applications: ['Property launch films', 'Sales galleries', 'Developer presentations', 'Digital signage', 'Web', 'Investor presentations', 'Social cutdowns'],
    featured: true,
    accent: '#c6a172',
  },
  {
    id: 'micro-stories-001',
    collection: 'micro-stories',
    collectionLabel: 'Micro Stories',
    index: '001',
    title: "Girls' Night",
    conceptLine: 'Three friends. One photo. One very bad idea.',
    sector: 'Narrative / Branded Entertainment',
    status: 'ATELIER POC',
    hero: {
      type: 'video',
      thumbnail: 'portfolio/showroom/micro-stories/concept-001/thumbnail.webp',
      youtubeId: 'tU8m1u80onE',
      duration: '00:30',
    },
    watchUrl: 'https://youtu.be/tU8m1u80onE',
    description: 'Three characters, one room and a tiny conflict. A 30-second AI-native narrative experiment focused on dialogue, acting, character continuity and cinematic direction.',
    extendedDescription: "Three friends. One photo that should probably not be posted. A little teasing — and a very predictable pillow fight. Built as a proof of concept for AI-native narrative production, Girls' Night focuses on consistent synthetic characters, Mexican Spanish dialogue, lip sync, micro-expressions, blocking, camera direction, physical interaction and believable chemistry.",
    territories: ['Branded Entertainment', 'Short-form Fiction', 'Character Campaigns', 'Lifestyle', 'Social Storytelling', 'Episodic Content'],
    capabilities: ['Character continuity', 'Multi-character performance', 'Mexican Spanish dialogue', 'Lip sync', 'Micro-acting', 'Narrative blocking', 'Physical interaction', 'Prop and fabric behavior', 'Cinematic direction', 'Short-form storytelling'],
    applications: ['Branded entertainment', 'Short-form campaigns', 'Episodic social content', 'Narrative commercials', 'Character-led campaigns', 'Teasers', 'Web', 'Social'],
    featured: true,
    latest: true,
    latestType: 'story',
    accent: '#b98278',
  },
]

export const projectsForShowroomCollection = (collectionId: string) => showroom
  .filter((project) => project.collection === collectionId)
  .sort((a, b) => a.index.localeCompare(b.index))
